# Generated by Django 5.0.3 on 2024-09-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_issue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('approved', 'Approved'), ('not_approved', 'Not_Approved')], default='not_approved', max_length=15),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
