# Generated by Django 5.0.3 on 2024-08-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myapiuser',
            old_name='name',
            new_name='username',
        ),
    ]
