[tool.black]
line-length = 88
target-version = ['py311']  # Update to Python 3.11
include = '\.pyw?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/migrations/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
sections = [
    "FUTURE",
    "STDLIB",
    "DJANGO",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
    "REST_FRAMEWORK"
]
known_django = ["django", "django_filters"]
known_rest_framework = ["rest_framework", "rest_framework_simplejwt"]
known_first_party = ["my_api", "channels"]
skip = ["migrations"]